### ISSUE TITLE
A11y checklist for further work

### ISSUE THREAD

**Issue by niknii-vincit** [HSLdevcom/jore4#1392]
Go through the results of the [Accessibility Audit](https://docs.google.com/presentation/d/1ePFbPmTUUK8m5-11lZZMlUyMNefIVyOrLa_SrK17pCc/edit#slide=id.g1e3be12a1f7_0_39), and create [grouped tasks](https://dev.azure.com/hslfi/JORE%204.0/_wiki/wikis/JORE-4.0.wiki/2488/Accessibility-tasklist) based on the findings, for further Ticket definitions.

- [x] Go through a11y checklist
- [x] Group and redefine them
- [x] Review with @HenrikHartiala and @juhakolari 
- [x] Tickets created after the review
