### ISSUE TITLE
Import scheduled stop points from the importer schema to the Jore 4 transmodel schema

### ISSUE THREAD

**Issue by pkainulainen-vincit** [HSLdevcom/jore4#514]
Add a new Spring Batch `Flow` to the jore4-jore3-importer Spring Batch `Job`. This flow:

1. Reads scheduled stop points from the `network.scheduled_stop_points` database table which is found from the database used by the jore4-jore3-importer.
2. Creates a scheduled stop point which contains the information that can be written to the Jore 4 database. This step must follow these steps:
   1. Find the information of the Digiroad stop by using ely number as a search criteria.  
   2. Read the following information from the found Digiroad stop: coordinates (X,Y), link id, and direction of the stop. 
   3. Create a new scheduled stop point which contains the information read from the Digiroad stop and uses the name of the scheduled stop point as a label of the new transmodel stop.
3. Inserts the transformed data into the `internal_service_pattern.scheduled_stop_points` table which is found from the Jore 4 database.

**Tasks**

- [x] Ensure that Jore4-jore3-importer imports only bus stops (PR closed as unnecessary)
- [x] Import Digiroad stops to a CSV file.
- [x] Import infrastructure link type from the Jore 3 database to the `network.scheduled_stop_points` table of the import schema (This isn't needed. We can get this information directly from the import schema). 
- [x] Read the scheduled stop point from the `network.scheduled_stop_points` database table.
- [x] Transform the information of the scheduled stop point into a format that can be written to the `internal_service_pattern.scheduled_stop_points` table.
- [x] Run all dependencies (including Jore 4 database) with Docker.
- [x] Ensure that jOOQ generates query classes from Jore 4 database.
- [x] Ensure that the import job inserts the imported scheduled stop points into the `internal_service_pattern.scheduled_stop_points` table found from the Jore 4 database.
- [x] Configure the Spring Batch flow which exports scheduled stop points to the Jore 4 database. (in review)
- [x] Clean routes, lines, and scheduled stops from Jore 4 database before the scheduled stop points are inserted into the database. (done, waiting for review)
- [x] Don't use the Finnish name as the label of the scheduled stop point which is inserted into the `internal_service_pattern.scheduled_stop_points` table. The real label can be queried from the Jore3 database. (done, waiting for review)

**Comment by pkainulainen-vincit** [comment]
Before I could start working on this issue, I had to ensure that the jore4-jore3-importer imports only bus stops. Here is a PR which contains the required changes: https://github.com/HSLdevcom/jore4-jore3-importer/pull/40
